version: 0.2

phases:
  build:
    commands:
      - ./mvnw clean generate-resources package

artifacts:
  files:
    - target/spring-petclinic-2.4.5.jar
    - appspec.yml
    - start.sh
    - stop.sh
    - validate.sh

cache:
  paths:
    - '/root/.m2/**/*'
